name: deep_links
description: Plugin for deep or dynamic links
version: 0.0.1
author: Softwine
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_dynamic_links: ^2.0.2
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
