name: push_notification
description: Notifications via firebase messaging
version: 0.0.1
author: Softwine
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^10.0.6
  rxdart: ^0.26.0
  flutter_local_notifications: ^9.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
