name: google_authentication
description: A new flutter plugin project.
version: 0.0.1
author: Softwine

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.1.3
  firebase_core: ^1.6.0
  google_sign_in: ^5.4.0
  rxdart: ^0.26.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.google_authentication
        pluginClass: GoogleAuthenticationPlugin
      ios:
        pluginClass: GoogleAuthenticationPlugin

  assets:
    - assets/
    - assets/images/
