name: update_form
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  multi_select_flutter: ^4.0.0
  googleapis_auth: ^1.1.0
  rxdart: ^0.27.1
  googleapis: ^3.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
