name: apple_authentication
description: A new Flutter package project.
version: 0.0.1
author:

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.1.4
  rxdart: ^0.26.0
  logger: ^1.0.0
  firebase_core: ^1.1.0
  crypto: ^3.0.0
  sign_in_with_apple: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
