name: authorization_bloc
description: A new Flutter package project.
version: 0.0.1
author: Softwine
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^3.0.0
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  dart_jsonwebtoken: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: