name: user_sync
description: User synchronization package
version: 0.0.1
author: Softwine
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: