name: terms_and_conditions
description: A new flutter plugin project.
version: 0.0.1
author:

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.1
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.terms_and_conditions
        pluginClass: TermsAndConditionsPlugin
      ios:
        pluginClass: TermsAndConditionsPlugin

  assets:
    - assets/terms_and_conditions.md