name: faculty_list
description: A list of faculties.
version: 0.0.1
author: Softwine 
homepage:
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0-nullsafety
  shimmer: ^2.0.0-nullsafety.0
  faculty_list_abstractions: 
    path: ../faculty_list_abstractions


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: