name: faculty_list
description: A new Flutter package project.
version: 0.0.1
author: Softwine 
homepage:
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "1.0.2"
  cloud_firestore: ^1.0.2
  cached_network_image: ^3.0.0-nullsafety
  shimmer: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: