name: faculty_list
description: A list of faculties.
version: 0.0.1
author: Softwine

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  notification_permissions: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: