name: zhytomyr_polytechnic
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  terms_and_conditions:
    path: ./features/terms_and_conditions
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.5.1
  rxdart: ^0.26.0
  fluttertoast: ^8.0.3
  firebase_core: ^1.6.0
  faculty_list: 
    path: features/faculty_list
  provider: ^5.0.0
  google_authentication:
    path: ./features/google_authentication
  group_selection:
    path: ./features/group_selection
  error_bloc:
    path: ./features/error_bloc
  timetable:
    path: ./features/timetable
  navigation_drawer:
    path: ./features/navigation_drawer
  contacts:
    path: ./features/contacts
  push_notification:
    path: ./features/push_notification
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.7
  user_sync:
    path: ./features/user_sync
  deep_links:
    path: ./features/deep_links
  apple_authentication:
    path: ./features/apple_authentication
  flutter_phoenix: ^1.0.0
  update_check:
    path: ./features/update_check
  url_launcher: ^6.0.10
  facebook_authentication:
    path: ./features/facebook_authentication
  package_info: ^2.0.2
  firebase_crashlytics: ^2.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/ 
