name: facebook_authentication
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.4.0+1
  firebase_auth: ^1.1.3
  firebase_core: ^1.6.0
  rxdart: ^0.26.0
  logger: ^1.0.0
  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
