name: group_selection_screen
description: A new flutter plugin project.
version: 0.0.1
author:

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.group_selection_screen
        pluginClass: GroupSelectionScreenPlugin
      ios:
        pluginClass: GroupSelectionScreenPlugin

  assets:
    - assets/images/
