name: Ios build & upload to Firebase App Distribution 

on:
  push:
    branches:
    - main
    
  workflow_dispatch:

jobs:
  build_ios:
    runs-on:	macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: |
        cd src
        flutter pub get
        flutter build ipa --export-options-plist=ios/ExportOptions.plist        
    - name: Upload iPA
      uses: actions/upload-artifact@v2
      with:
        name: ios-build
        path: src/build/ios/ipa
  beta_ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [build_ios]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ios-build
        path: ios-build
    - name: Upload IPA
      uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
      with:
        appId: ${{secrets.FIREBASE_APP_ID_IOS}}
        token: ${{secrets.FIREBASE_TOKEN}}
        file: "Житомирська політехніка.ipa"
