name: Ios build & upload to Firebase App Distribution 

on:
  push:
    branches:
    - main
    
  workflow_dispatch:

jobs:
  build_ios:
    runs-on:	macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: |
        cd src
        flutter pub get
        flutter clean
        flutter build ios --release --no-codesign   
        cd build/ios/iphoneos
        mkdir Payload
        cd Payload
        ln -s ../Runner.app
        cd ..
        zip -r app.ipa Payload  
    - name: Upload IPA
      uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
      with:
        appId: ${{secrets.FIREBASE_APP_ID_IOS}}
        token: ${{secrets.FIREBASE_TOKEN}}
        file: src/build/ios/iphoneos/app.ipa
