name: CI

on:
  push:
    branches: 
      - new_branch

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2.3.4
       
     - uses: subosito/flutter-action@v1
       with:
         channel: "stable"

     - run: flutter pub get

     - run: flutter analyze

     - run: flutter test             
         
